version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    env_file: ./.env
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    volumes:
      - .:/myapp
    volumes_from:
      - cache

  cache:
    image: busybox
    volumes:
      - /cache

  client:
    image: danlynn/ember-cli:2.5.1
    volumes:
      - ../tge-admin-client:/myapp
    command: server --watcher polling --proxy=http://web:3000
    links:
      - web
    ports:
      - "4200:4200"
      - "49152:49152"
