version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"

  web:
    build: .
    tty: true
    stdin_open: true
    env_file: ./.env
    command: bundle exec rails s
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    volumes:
      - .:/myapp
