# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bf787278c56f0dd4608809ebdd1ebacacd649647ec07af28df853edfbd06c73ea647271acdefb4b9fc1add72e3ba47366519b66943f3fa08a93beb0c9bbd28f

test:
  secret_key_base: 72106ac44d058b7853992a206e728603fe7c19d8aed04fbe3d527fc2077c9cbd7d512003fed3f1994777d9b3a420eefcacb52127661efac38054f14128bac231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
